FEEDS = [
    ('Sono Bisque Doll wa Koi wo Suru', 'https://weebcentral.com/series/01J76XYCMP8059QS9PDPHBMEQW/rss'),
    ('Vinland Saga', 'https://weebcentral.com/series/01J76XY7FQY59WRK2YWX5T4E5N/rss'),
    ('Boku no Kokoro no Yabai Yatsu', 'https://weebcentral.com/series/01J76XYE3365XHXPKAF08K7007/rss'),
    ('Uzaki-chan wa Asobitai!', 'https://weebcentral.com/series/01J76XYCY3XPECGTB45VH24PYX/rss'),
    ('Fuufu Ijou, Koibito Miman', 'https://weebcentral.com/series/01J76XYCNG38W8199ZM1X6EH7H/rss'),
    ('Soredemo Ayumu wa Yosetekuru', 'https://weebcentral.com/series/01J76XYD70GCH5VYK1QTGKHPTK/rss'),
    ('Yuusha ni Zenbu, Motodou...', 'https://weebcentral.com/series/01J76XYG81J8DTDXMNKHWRHR64/rss'),
    ('Parallel Paradise', 'https://weebcentral.com/series/01J76XYC3MVEYYP9QZ95DX8XZQ/rss'),
    ('Kakkou no Iinazuke', 'https://weebcentral.com/series/01J76XYD84FKQ5M54T1NC9TPJ0/rss'),
    ('One Punch Man', 'https://weebcentral.com/series/01J76XY7KT7J224EBK6J816Y1Q/rss'),
    ('Jujutsu Kaisen', 'https://weebcentral.com/series/01J76XYCERXE60T7FKXVCCAQ0H/rss'),
    ("Frieren: Beyond Journey's End", 'https://weebcentral.com/series/01J76XYDGDQERFSK333582BNBZ/rss'),
    ('100 Girlfriends Who Really, Really, Really, Really Love You', 'https://weebcentral.com/series/01J76XYD8VCP2FN1Q8E31RQ9GJ/rss'),
    ('Kaoru Hana wa Rin to Saku', 'https://weebcentral.com/series/01J76XYFHFZ88R32BW3RXHN1WP/rss'),
    ('Blue Box', 'https://weebcentral.com/series/01J76XYEMXXHG63FKC2DMTNC7B/rss'),
    ('Fly Me to the Moon', 'https://weebcentral.com/series/01J76XYCFK6GNRF6H17BZTKH2K/rss'),
    ('Class no Daikirai na Joshi to Kekkon suru Koto ni Natta', 'https://weebcentral.com/series/01J76XYG3NT7CTV59CSM1DTTGX/rss'),
    ('2.5 Dimensional Seduction', 'https://weebcentral.com/series/01J76XYDYRFJ3VB67F2JTGMY54/rss'),
    ('Grand Blue', 'https://weebcentral.com/series/01J76XYBWA1TEW2EBDYC9E3C9G/rss'),
    ('The Apothecary Diaries', 'https://weebcentral.com/series/01J76XYCCTKZ5GDQ05600AG7TQ/rss'),
    ('Tune In to the Midnight Heart', 'https://weebcentral.com/series/01J76XYGRASXCSBDH445TKVE1Y/rss'),
    ('Boku no Kanojo wa Dekkawaii', 'https://weebcentral.com/series/01JS4HKCW5BXEVRVTNNYRAAY6H/rss'),
    ('Kanan-sama wa Akumade Choroi', 'https://weebcentral.com/series/01J76XYFNTE9FGX5NVG1K3H8D3/rss'),
    ('Isekai Kaeri no Yuusha wa, Dungeon ga Shutsugen shita Genjitsu Sekai de, Influencer natte Kane wo Kasegimasu!', 'https://weebcentral.com/series/01JNV863SCX92GWQN045KBF0WM/rss'),
    ('Smoking Behind the Supermarket with You', 'https://weebcentral.com/series/01J76XYFP55025PVETS8GD9B6B/rss'),
    ('Backstabbed in a Backwater Dungeon - My Party Tried to Kill Me, But Thanks to an Infinite Gacha I Got LVL 9999 Friends and Am Out For Revenge', 'https://weebcentral.com/series/01J76XYF5PG8880XXPS1B80VVR/rss'),
]
